use_frameworks!

platform :ios, '9.0'

target 'MKBeaconXButton_Example' do
  pod 'MKBeaconXButton', :path => '../'

  target 'MKBeaconXButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
